"""Add foreign key constraint for user_id in URLs

Revision ID: ee983836750f
Revises: 4f61021ce1a3
Create Date: 2024-03-15 07:55:11.746806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee983836750f'
down_revision: Union[str, None] = '4f61021ce1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_url_user_id", "urls", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_url_user_id", "urls", type_="foreignkey")

    # ### end Alembic commands ###
